### ISSUE TITLE
自适应每列的高度

### ISSUE THREAD

**Issue by xiaoyao20084321** [flyOfYW/YWTableExcel#1]
能否实现自适应每列的高度啊
![image](https://user-images.githubusercontent.com/10344550/114818203-f1888c80-9ded-11eb-8dea-b9fe60b5efb2.png)

**Comment by flyOfYW** [comment]
你有什么好的思路实现吗

**Comment by xiaoyao20084321** [comment]
我的想法是， 能不能暴露出来设置每行的高度给到外界,让外界遍历数组里面的字符串进行计算高度， 然后设置每行高度就好了

**Comment by flyOfYW** [comment]
接口已提供
