### ISSUE TITLE
请问下如何设置每个cell的样式？比如第一列显示图片，第二列显示文字加图表？希望大佬可以回答下

### ISSUE THREAD

**Issue by vlay1314** [flyOfYW/YWTableExcel#3]
请问下如何设置每个cell的样式？比如第一列显示图片，第二列显示文字加图表？希望大佬可以回答下。需要继承那个类来实现？@flyOfYW

**Comment by flyOfYW** [comment]
目前不支持列图片的，不过你可以改动下源码就可以了，在YWTableExcelCell中对UICollectionView的注册一个新的UICollectionViewCell和改动其代理方法就可以了
